export enum AppRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  HOD = 'HOD',
  HR = 'HR',
  TRANSPORT_AUTHORITY = 'TRANSPORT_AUTHORITY',
  EMP = 'EMP',
  PLANNING = 'PLANNING',
}

export enum RequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  ADMIN_APPROVED = 'ADMIN_APPROVED',
  ADMIN_REJECTED = 'ADMIN_REJECTED',
  DAILY_LOCKED = 'DAILY_LOCKED',
  TA_PROCESSING = 'TA_PROCESSING',
  GROUPING_COMPLETED = 'GROUPING_COMPLETED',
  TA_COMPLETED = 'TA_COMPLETED',
  HR_APPROVED = 'HR_APPROVED',
  HR_REJECTED = 'HR_REJECTED',
  DISPATCHED = 'DISPATCHED',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
  CANCELLED = 'CANCELLED',
}

export enum VehicleType {
  VAN = 'VAN',
  BUS = 'BUS',
}

export enum SelfRegRole {
  EMP = 'EMP',
  HOD = 'HOD',
}

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  INACTIVE = 'INACTIVE',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET = 'PASSWORD_RESET',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  SUSPEND = 'SUSPEND',
  REACTIVATE = 'REACTIVATE',
  LOCK = 'LOCK',
  ARCHIVE = 'ARCHIVE',
  IMPORT = 'IMPORT',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
}

export enum GroupStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  ADJUSTED = 'ADJUSTED',
  DISPATCHED = 'DISPATCHED',
}
